version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "gagneavecia"
    labels:
      - "security"
      - "dependencies"
    commit-message:
      prefix: "⬆️"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "security"
      - "github-actions"